# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=16)),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('expire', models.DateTimeField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
