# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('href_url', models.CharField(max_length=1024)),
                ('pic_url', models.CharField(max_length=1024)),
                ('note', models.TextField()),
                ('available', models.BooleanField(default=1)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
